"""Generate a project summary and export customer/order id lists.
Creates:
- project_summary.md
- customers_ids.txt
- orders_ids.txt

Run: python scripts/generate_project_summary.py
"""
import sqlite3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "crm.db"
OUT = ROOT / "project_summary.md"
CUST_IDS = ROOT / "customers_ids.txt"
ORD_IDS = ROOT / "orders_ids.txt"

if not DB.exists():
    print(f"DB not found at {DB}")
    raise SystemExit(1)

conn = sqlite3.connect(str(DB))
conn.row_factory = sqlite3.Row
cur = conn.cursor()

# Basic counts
cur.execute("SELECT COUNT(*) as cnt FROM customers")
customers_count = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) as cnt FROM orders")
orders_count = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) as cnt FROM tickets")
tickets_count = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) as cnt FROM escalations")
escalations_count = cur.fetchone()[0]
cur.execute("SELECT COUNT(*) as cnt FROM conversations")
conversations_count = cur.fetchone()[0]

# Sample customers (first 50)
cur.execute("SELECT id, name, email, plan, join_date, status FROM customers ORDER BY id LIMIT 50")
sample_customers = cur.fetchall()

# All customer ids
cur.execute("SELECT id FROM customers ORDER BY id")
all_customer_ids = [str(r[0]) for r in cur.fetchall()]

# All order ids
cur.execute("SELECT id, customer_id, product, amount, date, status FROM orders ORDER BY id")
all_orders = cur.fetchall()
all_order_ids = [str(r[0]) for r in all_orders]

conn.close()

# Write ids files
CUST_IDS.write_text("\n".join(all_customer_ids), encoding="utf-8")
ORD_IDS.write_text("\n".join(all_order_ids), encoding="utf-8")

# Create markdown summary
md = []
md.append("# Project Summary: Agentforce-inspired Support Agent")
md.append("")
md.append("## Overview")
md.append("This project is an Agentforce-inspired customer support AI with a SQLite CRM, LangChain/Groq (optional), FastAPI backend, and Gradio frontend.")
md.append("")
md.append("**Key features:**")
md.append("- SQLite `crm.db` with `customers`, `orders`, `tickets`, `escalations`, `conversations` tables")
md.append("- Deterministic `LocalSupportAgent` fallback and optional Groq LLM integration")
md.append("- FastAPI endpoints: `/chat`, `/history`, `/escalations`")
md.append("- Gradio UI with tabs: Chat, Escalations, History, Agent Reasoning")
md.append("")
md.append("## Repo files of interest")
md.append("")
md.append("- `app/agent.py` — agent wiring and `LocalSupportAgent`")
md.append("- `app/tools.py` — CRM tools: `customer_lookup`, `order_history`, `ticket_status`, `escalate_to_human`, `order_lookup`")
md.append("- `app/main.py` — FastAPI app")
md.append("- `gradio_app.py` — frontend UI")
md.append("- `scripts/generate_crm.py` — creates `crm.db` with fake data")
md.append("")
md.append("## Database summary")
md.append("")
md.append(f"- Customers: **{customers_count}**")
md.append(f"- Orders: **{orders_count}**")
md.append(f"- Tickets: **{tickets_count}**")
md.append(f"- Escalations: **{escalations_count}**")
md.append(f"- Conversations logged: **{conversations_count}**")
md.append("")
md.append("## Files generated by this script")
md.append("")
md.append(f"- Customers ID list: `{CUST_IDS.name}`")
md.append(f"- Orders ID list: `{ORD_IDS.name}`")
md.append("")
md.append("## Sample customers (first 50)")
md.append("")
md.append("| id | name | email | plan | join_date | status |")
md.append("|---|---|---|---|---|---|")
for r in sample_customers:
    md.append(f"| {r['id']} | {r['name']} | {r['email']} | {r['plan']} | {r['join_date']} | {r['status']} |")

md.append("")
md.append("## Notes and next steps")
md.append("")
md.append("- To run the backend: `python -m uvicorn app.main:app --host 127.0.0.1 --port 8001`")
md.append("- To run the frontend: `python gradio_app.py` (set `API_URL` env var if needed)")
md.append("- Evaluation script: `scripts/evaluate.py`")

OUT.write_text("\n".join(md), encoding="utf-8")
print(f"Wrote {OUT} and id lists: {CUST_IDS}, {ORD_IDS}")
